# Build stage
FROM node:20.12.1-alpine AS builder
LABEL maintainer="Abdul Hadi <hi@ahadiwasti.com>"

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .
RUN npm run build

# Production stage (nginx)
FROM nginx:stable-alpine

WORKDIR /app

COPY --from=builder /app/out /app
COPY .nginx/nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]